afni/afni

- .gitignore
- src/matlab/CheckBrikHEAD.m
- src/matlab/ErrEval.m
- src/matlab/HEAD_Rules.m
- src/matlab/RemoveExtension.m
- src/matlab/WriteBrik.m
- src/matlab/zdeblank.m
This PR touches a few files only and is far from complete, but adds the following:
- ignore temporary files in .gitignore
- support showing CheckBrikHead's warnings in the command window (so that a GUI is not required)
- use the builtin "warning" function to show warnings
- faster implementations for RemoveExtension and zdeblank
> minor enhancements to Matlab library

- src/pkundu/meica.py
xref http://afni.nimh.nih.gov/afni/community/board/read.php?1,149961,149961
> Fix version check in meica.py

- .travis.yml
that is just an initial attempt/proof of concept, for now solely automating build as instructed by docs
results should appear on my travis... if you enable travis for afni on travis-ci.org, they should also come back into the pool request
you are welcome to merge and fix it up or I will slowly try to make it work ;)
> rudimentary travis.yml setup to use documented list of depends and stock Makefile

- .travis.yml
> ENH: try ubuntu specific Makefile for build on ubuntu ;-)

- .travis.yml
- CMakeLists.txt
- tests/CMakeLists.txt
- tests/xvfb-driver
as I had it in the neurodebian package
This one sits on top of #30 which I had to have locally to make it all build.  So shouldn't be merged as is until decision on #30 is made (thus marked as WiP -- work in progress).  Let's now see if this all would work ;)
> NF: Extracted cmake configuration for running some rudimentary smoke tests

- src/plug_realtime.c
Addition of implementation of equation (6) from Kundu multi-echo paper (doi:10.1016/j.neuroimage.2011.12.028) to provided weighted summation (optimal combination) of multi-echo EPI data.
> RT addition for optimal combination of multi-echo data

- src/python_scripts/afni_proc.py
- src/python_scripts/afni_util.py
- src/python_scripts/gen_epi_review.py
- src/python_scripts/make_pq_script.py
Added exception handling to all os.chmod calls (for filesystems that do not support chmod operations).
> Added exception handling to all os.chmod calls.

- src/other_builds/dockerfiles/Dockerfile.centos6
- src/other_builds/dockerfiles/Dockerfile.centos7
- src/other_builds/dockerfiles/Dockerfile.debian9
- src/other_builds/dockerfiles/Dockerfile.ubuntu1404
- src/other_builds/dockerfiles/Dockerfile.ubuntu1604
These could be useful for testing source builds.
> Added dockerfiles for building from source

- src/avovk/cluster_doubleNOMASK.c
- src/avovk/cluster_floatNOMASK.c
Don't add absolute include-path to <>-includes
> Don't add absolute include-path to <>-includes

- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/README.md
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/RTfeed.config.sample
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/afniInterfaceRT/__init__.py
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/afniInterfaceRT/experiment.py
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/afniInterfaceRT/realtime.py
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/afniInterfaceRT/receiver.py
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/afniInterfaceRT/testOS.py
- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/demoExpt.py
This commit also provides the capability of doing neuro-feedback experiments with PsychoPy running on Windows.
> Adding example neuro-feedback experiment which uses PsychoPy

- src/roopchansinghv/PsychoPy-NeuroFeedback-Demo/demoExpt.py
…onstration experiment that depends on it.
> Adding handling of non-installation of PsychoPy for neurofeedback demonstration program.

- src/3dTcorrelate.c
- src/3ddata.h
- src/thd_correlate.c
Added basic support for partial correlations to 3dTcorrelate.
> Added basic support for partial correlation to 3dTcorrelate

- src/Makefile.macosx_10.14
Initial commit: 10.14 compatible makefile using homebrew instead of fink for dependencies.
> Mac 10.14 makefile with homebrew+conda

- src/R_scripts/3dMEPFM.R
I added "(submitted to Neuroimage)"
> Update in 3dMEPFM.R

- src/3ddata.h
- src/CMakeLists.txt
- src/CMakeLists_mri.txt
- src/CMakeLists_plugins.txt
- src/Makefile.INCLUDE
- src/afni.c
- src/afni.h
- src/afni_plugin.c
- src/thd_store_index.c
Let's see how this pull request thing works.
If there are any problems, JL get the blame.
If it works well, RWC gets the credit.
That seems fair to me!
> reconfigure dset_ijk code for JL

- .docker/afni_dev_base.dockerfile
- tests/scripts/utils/misc.py
- tests/scripts/utils/tools.py
When using datalad.api.get, the dataset argument should be
a datalad.api.Dataset instance as described in
https://github.com/datalad/datalad/issues/4023
> make fix for 0.12.0 datalad

- src/3dGroupInCorr.c
- src/R_io.c
- src/afni_cluster.c
- src/afni_open.c
- src/afni_whelp.c
- src/apsearch.c
- src/suma_afni_surface.c
- src/suma_datasets.c
- src/suma_help.c
- src/suma_objs.h
- src/suma_string_manip.c
- src/suma_suma.h
- src/suma_utils.c
- src/thd_Xdataset.c
- src/thd_atlas.c
- src/thd_getpathprogs.c
- src/thd_niml.c
- src/thd_statpval.c
- src/vol2surf.c
- src/whereami.c
Addresses the first part of issue #139
> Suma dataset extraction

- cmake/afni_project_dependencies.cmake
- src/CMakeLists_mri.txt
- tests/scripts/test_3dAllineate.py
- tests/scripts/test_3dClustSim.py
- tests/scripts/test_suma_gui.py
- tests/scripts/utils/misc.py
Attempting a transition in the Cmake build link libmri against giftiio
> Fix suma gii interface for Cmake build

- src/3dTstat.c
- src/CMakeLists_mri.txt
- src/Makefile.INCLUDE
- src/coxplot/coxplot.h
- src/mrilib.h
- src/thd_StatsPDL.c
- src/thd_StatsPDL.h
Added skewness, and kurtosis, to 3dTstat
> PDL in 3dTstat

- src/CMakeLists_binaries.txt
- src/Makefile.INCLUDE
- src/afni_history.c
- src/afni_history.h
- src/afni_history_laurenpd.c
- src/afni_history_rickr.c
> laurenpd_history

- src/jzosky/RetroTS.py
fixing if statement for reading in custom slice acquisition timing files (e.g. for multiband data)
> deindent RetroTS.py slice_order if statement

- src/afni_history_rickr.c
- src/thd_niftiread.c
do not convert nifti scaled shorts to float
> keep nifti scaled shorts

- src/R_scripts/3dMEPFM.R
This PR adds an integration operator to 3dMEPFM in order to estimate the innovation signal (i.e. the first derivative in time of the neuronal-related signal, which represents the neuronal-related signal as a piecewise constant as introduced in:
> Uruñuela, E., Jones, S., Crawford, A., Shin, W., Oh, S., Lowe, M., & Caballero-Gaudes, C. (2020). Stability-Based Sparse Paradigm Free Mapping Algorithm for Deconvolution of Functional MRI Data. Proceedings of the Annual International Conference of the IEEE Engineering in Medicine and Biology Society, EMBS, 2020-July, 1092–1095. https://doi.org/10.1109/EMBC44109.2020.9176137
> Add integration operator to 3dMEPFM

- src/R_scripts/3dMEPFM.R
This PR adds the following changes:
- Add if statement to only load the `genlasso` library when `rho` is different from zero.
- Hid the `-block` option from users as it is still under development.
> Load genlasso only if rho is different from zero

- src/scripts_install/@animal_warper
added user options for 3dQwarp via auto_warp.py inside @animal_warper.
> animal_warper qw_opts

- src/scripts_install/SurfLayers
- src/scripts_install/quickspecSL
two new programs for laminar fMRI (and more?)
> new programs: SurfLayers and quickspecSL (!)

- src/pbar.c
Extend reset of func range in AFNI GUI to include Glasbey colorbars.
> pbar.c: INT_CMAP value for Glasbey cbars, N-1

- src/python_scripts/scripts/abids_tool.py
> Adds encoding if needed for abids_tool.py

- src/python_scripts/scripts/afni_system_check.py
add new opt to ASC for simply ouputting number of available CPUs
> afni_system_check.py: add -disp_num_cpu opt

- src/afni_history_rickr.c
- src/thd_niftiread.c
Move processing of AFNI extension in NIFTI input to a separate function.
We plan to add checks of those extension fields against the new dataset.
> move to THD_nifti_process_afni_ext

- .circleci/config.yml
- src/CMakeLists_mri.txt
- src/SUMA/SUMA_X_objs.h
- src/afni_history_rickr.c
- src/editvol.h
- src/mrilib.h
- src/suma_help.c
- src/testcox.c
test circleci with more recent macos/xcode versions
> update xcode version for macos 10.15.5

- src/coxplot/pwritf.c
Reapply extern in generated pwritf.c.
> coxplot regen extern

- src/afni_history_rickr.c
- src/nifti/Updates.txt
- src/nifti/nifti2/CMakeLists.txt
- src/nifti/nifti2/nifti2_io.c
- src/nifti/nifti2/nifti_regress_test/cmake_testscripts/c22_copy_image.sh
- src/nifti/nifti2/nifti_regress_test/cmake_testscripts/install_linking_test.sh
- src/nifti/nifti2/nifti_regress_test/cmake_testscripts/newfiles_test.sh
- src/nifti/nifti2/nifti_regress_test/commands/c15.new.files
- src/nifti/nifti2/nifti_regress_test/commands/c22.copy_image
- src/nifti/nifti2/nifti_tool.c
- src/nifti/nifti2/nifti_tool.h
merge nifti_clib updates for -copy_image and -convert2dtype
> Nifti sync

- src/afni_history_rickr.c
- src/python_scripts/afnipy/afni_base.py
- src/python_scripts/afnipy/db_mod.py
- src/python_scripts/scripts/afni_proc.py
copy template to results dir
set uvar
add opt -tlrc_copy_base
> ap template

- src/R_scripts/3dLMEr.R
> 3dLMEr.R errors: maskval != 1; highlight input -nt==1

- src/python_scripts/afnipy/lib_system_check.py
> Adds CPU type to system check

- src/python_scripts/scripts/init_user_dotfiles.py
python version, to run from and or independently from '@uab'
> init_user_dotfiles.py

- src/afni_history_rickr.c
- src/python_scripts/afnipy/db_mod.py
- src/python_scripts/scripts/afni_proc.py
> ap ricor qc

- src/R_scripts/TRR.R
found while reviewing #450 , I guess code is not unittested so fail was not picked up ever before
> [DATALAD RUNCMD] fix condiiton typo in the TRR.R code

- src/Makefile.linux_centos_7_64
- src/Makefile.linux_fedora_35_shared
Notably including centos 7 for now.
> being de-seleniumation

- src/R_scripts/RBA.R
Fixing missing commas when lop$distROI == 'student'.
> Update RBA.R Bug FIX

- src/scripts_src/test.afni.prog.help
Put this old file back in place for a while.  Without it, (the pre-update) build_afni.py will confusingly fail, requiring one to put a new build_afni.py in place to build the new code.
Leave this here for a while.
> re-add old test script

- src/other_builds/OS_notes.macos_12_b_user.tcsh
- src/other_builds/OS_notes.macos_12_x86_64_b_user.txt
convert from somewhat copy-and-paste to an executable script
(syntax is now tcsh)
> mac install

- src/R_scripts/3dMVM.R
> 3dMVM: make error message more readable/parseable

- src/afni_history_rickr.c
- src/python_scripts/afnipy/lib_system_check.py
- src/python_scripts/afnipy/module_test_lib.py
- src/python_scripts/scripts/afni_system_check.py
Check flask and flask_cors as part of -check_all.
> Asc - display python library versions

- cmake/FindGTS.cmake
- cmake/afni_project_dependencies.cmake
- cmake/make_sure_afnipy_is_installed.sh
- src/XmHTML/CMakeLists.txt
- src/python_scripts/CMakeLists.txt
Old work by @leej3 and some additions by me. Work in progress for the time being
> Packaging additions

- src/afni_history_rickr.c
- src/gifti/gifti_xml.c
- src/thd_gifti.c
Previously, GIFTI writes (from AFNI) ignored the directory.
> PREFIX to HEADNAME

- src/SUMA/SUMA_AnalyzeTrace.c
- src/SUMA/SUMA_Color.c
- src/SUMA/SUMA_Color.h
- src/SUMA/SUMA_CreateDO.c
- src/SUMA/SUMA_DOmanip.c
- src/SUMA/SUMA_Engine.c
- src/SUMA/SUMA_HalloSuma.c
- src/SUMA/SUMA_MapIcosahedron.c
- src/SUMA/SUMA_SVmanip.c
- src/SUMA/SUMA_ScaleToMap.c
- src/SUMA/SUMA_define.h
- src/SUMA/SUMA_display.c
- src/SUMA/SUMA_driver.c
- src/SUMA/SUMA_input.c
- src/SUMA/SUMA_niml.c
- src/SUMA/SUMA_xColBar.c
- src/SUMA/SUMA_xColBar.h
Alpha "A" button functionality added to suma.  This is drivable.
Old (usually commented) debugging output removed.
> Suma leap2024

- src/plug_realtime.c
Cameron Craddock (CC) wrote this as part of realtime detrending
> Write detrend dataset to rts

- src/mri_dicom_hdr.c
> Include header that defined swab()

- src/nifti/nifticdf/CMakeLists.txt
I am just a messanger from the cmake-wise @leej3 at https://github.com/afni/afni/issues/639#issuecomment-2145703256
Supposedly closes #639
> Announce niftiio as PRIVATE for linking to prevent propagating linking against it

- src/3dRetinoPhase.c
- src/SUMA/GLUT/libglut/glut_input.c
- src/SUMA/SUMA_input.c
- src/afni_history_rickr.c
- src/f2c/dfe.c
- src/f2c/due.c
- src/f2c/err.c
- src/f2c/fmt.c
- src/f2c/iio.c
- src/f2c/lread.c
- src/f2c/lwrite.c
- src/f2c/rdfmt.c
- src/f2c/rsfe.c
- src/f2c/rsne.c
- src/f2c/sfe.c
- src/f2c/sue.c
- src/f2c/uio.c
- src/f2c/wref.c
- src/f2c/wrtfmt.c
- src/f2c/wsfe.c
- src/whirlgif.c
Allow building when changing from gcc-13 to gcc-14, which otherwise fails on implicit-ints.
> implicit int

- src/afni_history_rickr.c
- src/scripts_install/@update.afni.binaries
Add to @update.afni.binaries the ability to use build_afni.py
> Uab - use build_afni.py

- src/afni_history_rickr.c
- src/python_scripts/afnipy/lib_timing.py
- src/python_scripts/scripts/timing_tool.py
Add -show_tr_offset_stats, a more detailed version of -show_tr_stats.  Still want to add an evaluation of having a uniform distribution across the TR.
> tt.offsets

- src/python_scripts/afnipy/lib_apqc_tcsh.py
- src/python_scripts/scripts/apqc_make_tcsh.py
Start of updates to have APQC HTML generated even when AP has not been used for full processing.
> lib_apqc_tcsh.py: more main_dset cases, as fallbacks

- src/SUMA/SUMA_LocalStat.c
- src/afni_history_rickr.c
- src/afni_sumafunc.c
- src/plug_permtest.c
- src/ptaylor/3dDWUncert.c
> quiet possible uninit warnings

- src/thd_ttatlas_query.c
- src/thd_ttatlas_query.h
This time fixed the whereami tab report issue based off the master branch.
> fixed whereami tab reports - off the master branch

- src/3dXYZcat.c
- src/afni_history_dglen.c
- src/mri_catvol.c
Wrong increment only in X direction put extra zero volume in concatenated output
> 3dXYZcat bug extra volume

- src/afni_history_rickr.c
- src/python_scripts/afnipy/afni_util.py
- src/python_scripts/afnipy/lib_system_check.py
- src/python_scripts/scripts/afni_system_check.py
afni_util.py: truncate using optional 'ceil', and fix repeated scale
ASC: require flask and more...
> misc: afni_util, afni_system_check
