src/matlab/HEAD_Rules.m
This PR avoids using WordCount and GetWord, leading to O(n) instead of O(n^2) speed for n field names.
Also tabs have been replaced by spaces.
=> Matlab fast head rules

src/python_scripts/db_mod.py
The command `afni_proc.py -tlrc_base path/to/template+tlrc` fails when `template+tlrc` can't be found in `AFNI_GLOBAL_SESSION`, `AFNI_PLUGINPATH` or `AFNI_PATH`.  This patch preempts the search if the user specified the path to the template.
Additionally, if the template is a nifti file, afni_proc.py successfully generates a processing script, but that script fails while trying to create the group mask.
=> FIX: Template-related failures in afni_proc.py

src/matlab/CheckBrikHEAD.m, src/matlab/WriteBrikHEAD.m
Make the Matlab library more compatible with GNU Octave by replacing logical bit-wise operators ('&' and '|') by the short-circuit versions ('&&' and '||').
=> Matlab library: replace logical bit-wise operators 

src/parser.c, src/parser.f, src/parser.h, src/parser.inc
I've been wanting these functions for a while now, and I finally got around to doing something about it.
- `choose(n,a,b,c,...)` chooses the n-th element of a,b,c,...
(e.g., `choose(2,a,b,c)` is `b`)
- `ifelse(p,t,f)` is equivalent to `p ? t : f`
I basically just copied the changes in a02241d7c4c9ac318b736db8b4d93e1123992109 and tweaked.
This change has been tested some and seems to work, but it should still be looked over by someone who knew Fortran this morning. Also regenerating `parser.c` might be necessary.
```bash
$ ./ccalc 'ifelse(0,1,2)'
2.000000
$ ./ccalc 'ifelse(1,1,2)'
1.000000
$ ./ccalc 'ifelse(7.5,1,2)'
1.000000
$ ./ccalc 'ifelse(0,1,2,3)'
PARSER error  12: Wrong number of arguments     
IFELSE(0,1,2,3) 
.............#
parser error!
$ ./ccalc 'ifelse(0,1)'
PARSER error  12: …
```
=> ENH: Add `choose` and `ifelse` to ccalc and friends

src/XmHTML/Makefile, src/XmHTML/lib/Makefile
to workaround the side-effect of users setting up too fancy for dash to
handle PS4 prompts, leading to obscure failures
Closes: #31
=> BF(workaround): export PS4=+ within XmHTML Makefile

doc/afni_sphinx/background_install/install_instructs/steps_linux_ubuntu.rst
Addresses issue #34 raised by @yarikoptic.
``git blame`` lists @mrneont and @afni-rickr near the offending lines.
Before merging, please consider: I am not sure if the line with
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libgsl.so /usr/lib/libgsl.so.0
```
is supposed to be kept in or not; for now I kept it in.
=> remove git merge conflict lines

src/matlab/afni_niml_writesimple.m, src/matlab/unsplit_string.m
Minor changes in some of the Matlab code involved in writing NIML files. Fixes string formatting appended to NIML file history contents.
=> Matlab: minor refactoring and fix in setting call stack in NIML history

src/SUMA/SUMA_DataSets.h
Otherwise suma would crash with
freeglut  ERROR:  Function <glutBitmapWidth> called without first calling 'glutInit'.
upon right click on a mesh
Originally written: 2012-11-29
=> call glutInit in SUMA_STANDALONE_INIT

src/jzosky/lib_RetroTS/PhaseEstimator.py
Python uses half open ranges and matlab uses closed ranges. These produce identical results if there are not a round number of steps in the range , but when there are a round number of steps, Python will produce a range with one fewer value. This affected the time_series_time variable in PhaseEstimator.py, and this pull request addresses that case.
=> Retrots fix

.travis.yml
This addresses failing travis tests due to using the wrong `count` program.
Addresses #56; see also AFNI message board discussion at https://afni.nimh.nih.gov/afni/community/board/read.php?1,155735,155735#msg-155735
Thanks to @yarikoptic for PR #57.
=> Travis: set PATH variable so that afni binaries precede other binaries

.travis.yml
Just a wild guess while waking up
=> Make ctest run verbose

src/matlab/unsplit_string.m
Minor fix in the AFNI Matlab library.
``unsplit_string`` produces incorrect results if more than two strings are "unsplit". This results in incorrect NIML files being written.
ping @afni-rickr @afni-gangc
=> FIX: correct issue in AFNI Matlab library "unsplit_string" function

src/other_builds/Makefile.linux_openmp_64_centos6, src/other_builds/OS_notes.linux_centos_6.txt
These instructions work for building AFNI on CentOS 6, starting with a base/minimal installation.
=> Added notes for building on RedHat/CentOS 6

src/python_scripts/db_mod.py
Hello! 
The `-despike_mask` option flag to afni_proc.py seems to have no effect. 
Investigating this issue is the first time I've looked at the afni source, so this proposed change might be totally off the mark, but I think it addresses the problem. `-despike_mask` works as expected on my machine after making it, at least.
=> fix for -despike_mask option in afni_proc.py?

src/3dROIstats.c
Added ability to output full BRIK labels in 3dROIstats output.  Currently -longnames maxes out at 50 characters.
=> Can now output full BRIK labels in 3dROIstats with -longnames

src/python_scripts/afni_python/niml_parsing.py, tests/scripts/test_niml_parsing.py
this is planned to be used with niml output
from 3dinfo (not presently implemented)
It will also parse the niml element extracted
from the afni extension that is often saved in
a nifti header.
More extensive plans in this regard is to define
an xml schema for the niml element to allow
niml validation and automated parsing to the level
of typed arrays. This would also allow recursive
niml elements to be parsed with ease.
=> add rudimentary niml parsing

src/3DEdge/src/extrema.c, src/3dAFNItoNIML.c, src/3dTproject.c, src/3dfim+.c, src/3dmask_tool.c, src/3drefit.c, src/Makefile.linux_ubuntu_16_64, src/afni_func.c, src/debugtrace.h, src/float_scan.c, src/help_format.c, src/matrix_f.c, src/mayo_analyze.c, src/mcw_malloc.h, src/mrilib.h, src/niccc.c, src/niml/niml.h, src/plugout_ijk.c, src/plugout_tt.c, src/ptaylor/3dTrackID.c, src/ptaylor/DoTrackit.h, src/ptaylor/diffusiony.c, src/ptaylor/diffusiony.h, src/ptaylor/readglob.h, src/ptaylor/rsfc.c, src/siemens_vision.c, src/siemens_vision.h, src/thd_intlist.c, src/to3d.c
Fix all compiler warnings about implicit function declarations (warning: implicit declaration of function) in the default build configuration for Mac OS X 10.14 by including appropriate headers, using macros that were already defined for functions related to mcw_malloc, adding forward declarations, or by calling the correctly named function.
=> Fix implicit function declarations warnings

src/f2c.h, src/f2cdir/main.c, src/machdep.c, src/mcw_malloc.c, src/mcw_malloc.h, src/mri_quantize.c, src/replaceXt.h, src/suma_datasets.h, src/thd_dset_to_vectim.c
REPLACE_XT can now be used to swap out X11's memory allocation.
f2cdir  main.c does not need a main function because it is only
used as part of the f2cdir shared object library.
=> add c changes accumulated during build development

src/SUMA/SUMA_Makefile_NoDev, src/SUMA/SUMA_suma.h
This is a fix for linux. It still doesn't make a fix for the flat namespacing in the OSX SDK
=> include glut.h with appropriate name spacing

src/afni_setup.h
Using the CMake build of AFNI on macOS 10.15 with AppleClang, there are 107 instances of header-guard warning:
```
../src/afni_setup.h:7:9: warning: '_AFNI_SETUP_HEADER_' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
#ifndef _AFNI_SETUP_HEADER_
```
Correcting the defined macro eliminates these warnings.
=> Fix typo in macro _AFNI_SETUP_HEADER_ used as header guard

src/plug_realtime.c
A new communication method with the receiver has been added for the "All Data" configuration. In its original form the plugin would send 8 values per ROI voxel. With large ROI this can be a performance bottleneck. A new option "All Data (light)" has been added, that only sends one value per voxel. The old way of doing things remain under the label "All Data (heavy)"
=> New method for "All Data" communication

src/jzosky/RetroTS.py
This addresses the issue raised [here](https://afni.nimh.nih.gov/afni/community/board/read.php?1,155524,155524#msg-155524) 
it fixes errors thrown when only one of either respiration data file or cardiac data file is passed to the RetroTS.py.
It also automatically figures out what to write in output file based on the argument passed in.
=> Improved RetroTS.py

src/python_scripts/afnipy/lib_system_check.py, tests/scripts/test_with_afni_system_check.py
Handles the deprecation of platform.dist function in python 3.8.
solves #162
=> add fix from neurolabusc for lib_system_check.py

.circleci/config.yml
Pass the dev base image cache version as a parameter to
setup_dev_base_image command so that now all images have the same cache
version that is solely set in the workflow section.
Tidy working directory behavior:
Instead of setting working_directory rely on the fact that the
default is always ~/afni. It prevents irritating bugs where the
working_directory is not set correctly (although is unfortunately
implicit rather than explicit).
=> improve circleci image caching and WD management

.docker/afni_dev_base.dockerfile
Resolves https://github.com/afni/afni/issues/194
A singularity behavior change causes the docker image to now break on some
clusters after conversion to singularity. This change may be reverted in future
versions of singularity. But who needs the time in a container?
https://github.com/hpcng/singularity/issues/5465
EDIT: it's really just the work around that the change in singularity behavior fixes. Otherwise, the images are broken for usage with singularity on systems that bind in this way. Good to know... hopefully its fixed now
=> do not create contained time

tests/afni_test_utils/container_execution.py, tests/afni_test_utils/data_management.py, tests/afni_test_utils/minimal_funcs_for_run_tests_cli.py, tests/afni_test_utils/tools.py, tests/conftest.py, tests/scripts/test_guis.py, tests/scripts/test_ptaylor.py, tests/scripts/test_testing_script_functionality.py
Most substantial change is that test commands are now executed
asynchronously. This allows log output to be displayed in real
time and avoids an edge when sleeping process timeout instead
of returning an exit status.
=> Some miscellaneous improvements in testing

.docker/afni_dev_base.dockerfile, src/python_scripts/afnipy/afni_base.py, tests/afni_test_utils/container_execution.py, tests/afni_test_utils/data_management.py, tests/afni_test_utils/minimal_funcs_for_run_tests_cli.py, tests/afni_test_utils/tools.py, tests/conftest.py, tests/pytest.ini, tests/scripts/test_guis.py, tests/scripts/test_testing_script_functionality.py
exposes functionality implemented in pytest's conftest.py in the run_afni_tests.py CLI.
Test output logs are modified at the time of comparison to pre-existing sample data from a previous run. This modification reduces spurious diffs occurring.
Command trimming is disabled for stdout/err. This was causing some issues with spurious diffs in the output logs for tests.
Rewriting of paths has been made more robust (previously it was not always rewriting the paths correctly and the functionality was untested)
=> add fixes for local, test infrastructure path rewriting behavior, and extend cli of run_afni_tests.py

src/3dAFNItoNIFTI.c
Closes #244 
This moves the print statement to be after the help; however, it appears to suppress output of that line entirely. However, this behavior is consistent with what happens in 3dAFNItoNIML as well so I decided to open the PR anyway.
=> Moves print statement in 3dAFNItoNIFTI

src/afni_history_dglen.c, src/scripts_install/@Atlasize, src/scripts_install/@MakeLabelTable
atlasize and MakeLabeltable had issues with long name labels when used in combination with atlases, corrupting the short name labels. This fix should correct those problems with atlases that contain both short and long name labels.
=> dg_atlasize

.circleci/config.yml, CMakeLists.txt, src/CMakeLists_mri.txt, src/afni_history_rickr.c, src/crorden/dcm2niix_console/CMakeLists.txt, src/crorden/dcm2niix_console/makefile, tests/afni_test_utils/container_execution.py, tests/afni_test_utils/data_management.py, tests/afni_test_utils/minimal_funcs_for_run_tests_cli.py, tests/afni_test_utils/run_tests_func.py, tests/scripts/test_ptaylor.py, tests/scripts/test_testing_script_functionality.py
This tries to address the issues in publishing test data with datalad described in https://github.com/afni/afni_ci_test_data/issues/2. 
It also includes a breakage in tests that was fixed in https://github.com/afni/afni/pull/268 but it does not look like that is going to be merged.
A temporary fix for 3dClusterize tests where the output diffing does not occur is added for now to pass the tests until the test data is updated appropriately.
There is still an issue with the compilation of libmri on MacOS described here:
https://github.com/afni/afni/issues/278
Additionally suma is no longer compiling on MacOS... that error looks more extensive.
=> Make some ci fixes

src/afni_widg.c, src/pbar.c
Up until now, an INT_CMAP with N colors applies to an ROI dset with max value N, and sets its pbar max to also be N.
What *should* happen (and does happen now), is that an INT_CMAP with N colors applies to an ROI dset with max value N-1, and sets its pbar max to also be N-1.
=> Int cmap range

CMakeLists.txt
Sorry, missed this. Help messages aren't so helpful when they're wrong
=> fix compilers help message in CMake

.mailmap
Compare master:
$> git shortlog -sn | head -n 20
6007	rwcox
2803	rick reynolds
2378	ziad
2058	RWCox
1995	rickr
1675	mrneont
576	leej3
549	afniHQ
416	dglen
387	gangc
339	daniel glen
279	Ziad S. Saad
252	cox
244	Peter Lauren
170	Paul Taylor
160	gang chen
133	afni-gangc
121	discoraj
111	afni-rickr
78	Daniel Glen
to this branch:
$> git shortlog -sn | head -n 20
8352	Robert Cox
4985	Rick Reynolds
2711	Ziad S. Saad
1869	Paul Taylor
833	Daniel Glen
692	Gang Chen
592	John Lee
549	afniHQ
244	Peter Lauren
121	discoraj
68	Nikolaas N. Oosterhof
48	Paul Novak
40	afni-discoraj
38	Ubuntu
37	rhammett
36	Cameron Craddock
36	shotgunosine
34	Joshua Teves
31	Jakub Kaczmarzyk
28	Yaroslav Halchenko
PS believe me -- 20 was really an arbitrary cut off!!! ;)
=> Add .mailmap for more adequate  git shortlog -sn and unified naming in log

src/3dDiff.c
@pmolfese noted that I'm missing the compile date in 3dDiff's help, small patch to fix.
=> Adds compile date

src/other_builds/Makefile.linux_ubuntu_22_64
1) Remove wrong path - `glib-2.0/include`
2) Add include path for aarch64 - `-I/usr/lib/aarch64-linux-gnu/glib-2.0/include`
This is one of the changes suggested by @markjens at https://github.com/afni/afni/issues/390#issuecomment-1219148589. It seems it was never committed to the repository.
=> Fix SUMA_INCLUDE_PATH for the universal Makefile

src/afni_history_rickr.c, src/mri_3dalign.c, src/thd_automask.c
warn when trim (or other) sends weights to empty - ponder startup_lsqfit later
=> warn on trim error

src/python_scripts/scripts/align_epi_anat.py, src/simplex.c
Powell NEWUOA would provide NaNs (not a number) if a constraint min=max  for any parameter. While not a typical use case, it can be a test case and was causing problems with a specific test.
align_epi_anat.py would fail on the resample step if the anat and EPI datasets (dset1,2) had different view space inputs - one was ORIG, the other TLRC (tlrc view) (MNI, waxrat, ... any non-ORIG space). The view is now set for the resample to match the master, the anatomical dataset. That view is also applied appropriately in the subsequent step for the  EPI skullstripping/automasking step too.
=> Powell NEWUOA 

src/SUMA/SUMA_ConvertSurface.c, src/SUMA/SUMA_IsoSurfaceFunc.c, src/SUMA/SUMA_Surface_IO.c
This set of changes is in response to the issue of atypical ply surfaces. Intensity is an unnecessary element in the faces property that gets repeated with values of 1 through the output file. Also a collection of small fixes to remove warnings on build in the relevant file. @afni-rickr can you take a look and verify. There was a minor include update for the marching cubes for clang compatibility.
https://github.com/afni/afni/issues/452
=> ply surfaces without intensity, clang march fix and compiler warnings

src/python_scripts/afnipy/lib_system_check.py
@afni-rickr : how does this seem to include?  Xvfb is needed for `@chauffeur_afni`, and hence APQC HTML, etc.
=> ASC: add check (with 'please fix'-ability) for Xvfb

src/AFNI_atlas_spaces.niml
Small update to add labels to Haskins Pediatric atlas. The labels are not in the github repo, but the AFNI_atlas_spaces.niml file had to be updated to refer to the right version of the atlas. Removed affine versions of the template and atlas. These are available separately in the HaskinsPeds pub/dist/atlases directory of the AFNI website. Also updated the reference to the correct citation.
=> HaskinsPed atlas labels update

src/scripts_install/@chauffeur_afni
The input parameters of @chauffeur_afni for -func_resam expect one of NN, Li, Cu or Bk. The logic in the script reports an error because it is ORing those tests. This means you cannot use this functionality at all because it is impossible for the value to be all of those at once.
A simple inversion of the logical OR to AND and all is well.
We have tested this in our project, where we found the problem in the first place, and it resolves nicely.
=> @chauffeur_afni func_resample logic error

src/AFNI_atlas_spaces.niml, src/afni_widg.c, src/thd_ttatlas_query.c, src/thd_ttatlas_query.h
Fairly large list of changes to atlases and templates. Code changes for default atlases to use for Atlas colors and Go to atlas location and for default lists of atlases to search and default list of spaces to show in whereami.
Atlases and templates get a refresh/overhaul in AFNI_template_spaces.niml in the source.
Note this PR should be implemented simultaneously with atlas and template changes.
Seed-based correlations against the new specific MNI_2009c_asym, MNI_N27 will need to be allowed in afni_proc.py QC.
=> Non ttatlas

src/afni_history_dglen.c, src/thd_ttatlas_query.h, src/whereami.c
whereami -index_to_label _index_ -dset path_to_dset/dsetname
returns the label from the labeltable for the index in the dataset. Alternatively, provide "-atlas atlasname" to get the label from the atlas points list labels. These will almost always be the same, except for longnames in atlases.
=> index_to_label

src/thd_ttatlas_query.c
Left-right labels in an atlas name use could cut off regions that crossed 0,0,0 lines. This could happen even if the "left", "right", "both" were specified. Since abandoning the lr masks from the MNI_N27 and TT_N27 datasets, these were no longer used for left, right determination and weren't valid for other atlases in any case.
```
3dBrickStat -count -non-zero 'CA_ML_18_MNI::Left_SMA'
3dcalc -a CA_ML_18_MNI::Left_SMA -expr a ...
```
This solution removes the left or right label determination that is then used to mask the dataset based on 
coordinates.
=> atlas left-right label handling

src/afni_history_rickr.c, src/scripts_install/@Atlasize, src/scripts_install/@MakeLabelTable, src/scripts_install/@chauffeur_afni, src/scripts_install/compute_ROI_stats.tcsh, src/scripts_install/gen_cluster_table
This is a quick fix for biowulf usage, since there is a new whereami in town (/usr/local/bin/wheremai), and because they reset the PATH. Modify: @Atlasize @MakeLabelTable @chauffeur_afni compute_ROI_stats.tcsh gen_cluster_table
=> in any script calling whereami, envoke with tcsh -f at top

src/3dExchange.c, src/Makefile.macos_11_ARM_clang, src/SUMA/SUMA_clippingPlanes.c, src/SUMA/SUMA_glxdino.c, src/XmHTML/lib/Motif/motif.c, src/XmHTML/lib/common/psoutput.c, src/jpeg-6b/configure
gcc-14 is the latest default version for homebrew with `brew install gcc`. That latest version of gcc imposes some C code updates like requiring int declarations for functions that return integers. Updates to ignore some warnings with -Wno-implicit-int (f2c code built from Fortran would need to be updated with each conversion) and a couple small other declaration fixes solves the complaints of this version of the gcc compiler.
The libjpeg.a update only occurs in the configure command script it uses to determine compiler properties and not in the AFNI source code.
The libXmHTML code required two small changes for consistent type declarations.
=> Homebrew gcc-14 new requirements on C code

src/imseq.c
The ffmpeg -intra option was deprecated about 6 years ago and is now obsolete on homebrew's default version. Replaced the "-intra" with "-g 1".
=> ffmpeg parameter deprecation

src/python_scripts/afnipy/db_mod.py, src/python_scripts/scripts/align_epi_anat.py
python is viewing the \ chars as escapes, so they should be passed through to the shell
=> escape the escapes

src/plug_drawdset.c
The Draw Dataset plugin does not allow a radius smaller than 0.1mm for spherical and circular ROIs. This becomes an issue for volumes with very fine resolution, as sometimes seen with mouse, rat and marmoset imaging. This modification shifts the decimal point and allows changes down to 0.01mm.
=> allow smaller spheres in Draw Dataset

src/R_scripts/RBA.R
The CLI call `RBA -mean 'Y~1+Fac+(1+Fac|Subj)+(1+Fac|ROI) -EOI 'Fac' ...` results in the plotting error `Error: object 'nR' not found` due to line 1297 attempting to use the variable `nR` which was not set (line 789) as the `-mean` option and not `-model` was used in the call.
Adding line 1294 resolves this issue but reveals the error 
```
Error in `[<-`(`*tmp*`, jj, , , value = psROI(aa, bb, paste0(lop$EOIc[ii],  : 
subscript out of bounds
```
which stems from lines 1292, 1293 attempting to count factors which were never set (line 789) for the same reason as above. Updating these lines resolves this error.
=> fix plotting issue when mean opt used

doc/README/README.environment, src/afni_history_dglen.c, src/thd_initsess.c
This update sorts datasets in the AFNI GUI dataset choosers like Underlay and Overlay choosers. Previously, datasets were ordered in an apocryphal order related to their dataset type and their data format with anatomical datasets first, followed by all other types. AFNI format was  included first and then NIFTI and other types of datasets.
The new orders allow for simple alphabetic, reverse alphabetic, dataset type (anatomical, echo planar, functional bucket - a little like the original, but includes NIFTI), or the default order the datasets are read in (close to the original method). I haven't preserved the real original sort, but that could be added in if someone wants that.
Tested with datasets with mixed spaces and formats. Read in new sessions, added new datasets after reading …
=> Sort datasets in dataset choosers 

src/python_scripts/afnipy/db_mod.py
@afni-rickr : 
What do you think about this change in handling polort values for 3dToutcount?  This was prompted by a case in which a user had `-regress_polort -1`, which created a failure later on down the road in the proc script execution.
Separately, 3dToutcount fails with polort <0, but with the wrong error message, so I am going to edit that in the master branch.
Basically, 3dToutcount cannot have a polort <0.  This puts a check for that earlier on, and fails if a user advertently or inadvertently creates a situation for that.  But there may be better ways to implement this in the code.  I have greatly expanded the number of lines in this function...
=> AP suggestion: handle/fail differently for polort<0 in 3dToutcount
